version: '3'

tasks:
  install:
    dir: ansible
    cmds:
      - ansible-playbook playbooks/install.yaml
    silent: false
  reset:
    dir: ansible
    cmds:
      - ansible-playbook playbooks/reset.yaml
    silent: false
  upgrade:
    dir: ansible
    cmds:
      - ansible-playbook playbooks/upgrade.yaml
    silent: false
  bootstrap:
    cmds:
      - ./scripts/terragrunt.sh all apply
