
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test
  namespace: external-secrets
spec:
  secretStoreRef:
    kind: SecretStore
    name:  1password-connect-store
  target:
    creationPolicy: Owner
  data:
    - secretKey: MY_ENV_VAR1
      remoteRef:
        key: argocd
        property: credentials
