apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: connect
    repo: https://1password.github.io/connect-helm-charts
    releaseName: 1password
    namespace: 1password
    additionalValuesFiles:
      - values.yaml
    version: "1.14.0"

resources:
  - namespace.yaml

