#!/bin/bash

usage() {
    cat <<EOM
  Usage:
    $(basename $0) boot-init [node_id]
      e.g. boot-init 0 -> setup master node

EOM
    exit 0
}

[[ $# < 1 ]] && { usage; }
node_id=$1
user="nandi"
hostname="node-rpi-$1"

k3s_version="v1.28.2+k3s1"
k3s_mode="master"

K3S_ARGS="--cluster-cidr 10.45.0.0/16 --service-cidr 10.50.0.0/16 --cluster-dns 10.50.0.1 --node-name=rpi-node-$node_id"
INSTALL_K3S_EXEC=""
if [[ "$node_id" == "0" ]]; then
  # server mode
  INSTALL_K3S_EXEC="server $K3S_ARGS --node-label role=server"
else
  # client mode
  INSTALL_K3S_EXEC="client $K3S_ARGS --node-label role=agent"
fi





[[ ! -f /Volumes/system-boot/user-data ]] && echo "Volume not mount. Make sure the SD-Card is inserted." && exit 1

echo "writing cloud-init at /Volumes/system-boot/user-data ..."
cat << EOF > /Volumes/system-boot/user-data
#cloud-config

apt_upgrade: true
apt_update: true

# disable password auth
ssh_pwauth: false

# Set TimeZone and Locale
timezone: America/Toronto
locale: en_US.UTF-8

# Hostname
hostname: "$hostname"

# cloud-init not managing hosts file. only hostname is added
manage_etc_hosts: localhost


# provide custom CA cert
ca_certs:
  remove_defaults: false

  # add the trusted CAs
  trusted:
  - |
$(cat credentials/certs/intermediate/cert.pem | awk '{print "    "$0}' )
  - |
$(cat credentials/certs/root-ca/cert.pem | awk '{print "    "$0}' )

users:
  # not using default ubuntu user
  - name: "$user"
    primary_group: users
    groups: [adm, admin]
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: true
    ssh_authorized_keys:
      - "$(cat ~/.ssh/id_rsa.pub)"

runcmd:
  # per https://github.com/k3s-io/k3s/issues/4234
  - apt install -y linux-modules-extra-raspi
  - curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION="$k3s_version" INSTALL_K3S_EXEC="$INSTALL_K3S_EXEC" sh -

EOF

echo "done."
echo ""
echo "writing cmdline.txt at /Volumes/system-boot/cmdline.txt ..."

# https://docs.k3s.io/advanced#raspberry-pi
cat << EOF > /Volumes/system-boot/cmdline.txt
net.ifnames=0 dwc_otg.lpm_enable=0 console=serial0,115200 console=tty1 root=LABEL=writable rootfstype=ext4 elevator=deadline rootwait fixrtc cgroup_enable=memory cgroup_memory=1
EOF

echo "done."
echo ""
