---
k3s_cluster:
  children:
    server:
      hosts:
        10.43.2.1: {}
        10.43.2.2: {}
        10.43.2.3: {}


  # Required Vars
  vars:
    ansible_port: 22
    ansible_user: nandi
    k3s_version: v1.28.2+k3s1
    api_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"
    extra_server_args: "--cluster-cidr 10.45.0.0/16 --service-cidr 10.50.0.0/16 --cluster-dns 10.50.0.100 --disable traefik --disable-network-policy --disable servicelb"
    extra_agent_args: ""
