apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: argocd
    repo: https://argoproj.github.io/argo-helm
    releaseName: argocd
    namespace: argocd
    additionalValuesFiles:
      - values-upstream.yaml
      - values.yaml
    version: "5.46.8"
    

resources:
  - external-secret.yaml
  - service.yaml

